### ISSUE TITLE
Change module requirement to package, not recipe

### ISSUE THREAD

**Issue by sminnee** [Firesphere/silverstripe-haveibeenpwnd#1]
Recipes are collections of packages to streamline the creation of new projects.

Modules shouldn't use them as their dependencies, otherwise you're saying that the module can't be used except with that specific recipe. This prevents the creation of custom recipes.

Instead, this module should list as dependencies only those modules that you make specific reference to. This is probably silverstripe/cms.

**Comment by Firesphere** [comment]
Acknowledged and agreed :) I use it often to get CircleCI started quickly (And then (forget to) clean up after myself)

**Comment by Firesphere** [comment]
This better? I want recipe-cms to unit test the optional pages

**Comment by sminnee** [comment]
Yeah that seems reasonable.

**Comment by Firesphere** [comment]
Testing child pages on a module that doesn't explicitly need the CMS is a tad tricky some times :)
